### PR TITLE
sc: bump version, rename gene id attribute

### PR DESCRIPTION
**Pull request by JakaKokosar**
Refers to: https://github.com/biolab/orange3-single-cell/issues/189

Attribute name for Gene ID was renamed to Entrez ID

### CODE REVIEW

**Comment by lanzagar** [comment]
I see the version changes but nothing else...?

**Comment by JakaKokosar** [comment]
FIles were updated, renamed gene attribute from 'Gene ID' to 'Entrez ID'

**Comment by lanzagar** [comment]
Files were already updated, directly on the server?
So this PR is just a retroactive version bump for an already made change?

**Comment by lanzagar** [comment]
OK so it turns out this is not a retroactive change, new urls have now been added to the PR, and everything makes sense now.
Merging.

**Pull request merged**
