### PR TITLE
Human pancreas data

### PR DESCRIPTION
**Pull request by iva-c**

### CODE REVIEW

**Comment by pavlin-policar** [comment]
Can this be merged? We'd really need it ASAP.

`baron2016_pancreas_human.pkl.gz` doesn't seem to exist on the [server](https://datasets.biolab.si/sc/) though.

**Comment by mstrazar** [comment]
@pavlin-policar can you check with @iva-c what is the status of the file and/or upload it to the server.

**Comment by BlazZupan** [comment]
@iva-c won't be available in the next two weeks, @pavlin-policar can you make another PR and close this one?

**Comment by pavlin-policar** [comment]
Working on it as we speak. Unfortunately, I don't have permissions to close this. Or merge my own PR when it's done for that matter. Would be great if I had them.

**Comment by pavlin-policar** [comment]
I've located the file on http://file.biolab.si/scdata/, but it doesn't load properly into Orange, so I guess that's why the PR wasn't accepted. I'll prepare one myself.

**Comment by iva-c** [comment]
If you need the unprocessed data, I can send it to you.

**Comment by lanzagar** [comment]
Replaced by #86 and #89

**Pull request closed without merging**
